- storage-nvmf/src/main/java/org/apache/crail/storage/nvmf/NvmfStorageConstants.java
Set keep alive interval to lower value to not run into the
situation where we missed the keep alive deadline and the connection
is shutdown by the controller.
https://issues.apache.org/jira/browse/CRAIL-32
> NVMf: decrease keep alive interval

- CREDITS
- DISCLAIMER
- HISTORY.md
- NOTICE
This pull request moves the IBM copyright from the NOTICE file to the CREDITS file and adds the Apache incubator disclaimer.
> copyright & disclaimer

- client/src/main/java/org/apache/crail/CrailStore.java
- client/src/main/java/org/apache/crail/conf/CrailConstants.java
- client/src/main/java/org/apache/crail/memory/MappedBufferCache.java
- client/src/main/java/org/apache/crail/storage/StorageClient.java
- client/src/test/java/org/apache/crail/ClientTest.java
- conf/core-site.xml.template
- conf/crail-site.conf.template
- storage-narpc/src/main/java/org/apache/crail/storage/tcp/TcpStorageConstants.java
- storage-narpc/src/main/java/org/apache/crail/storage/tcp/TcpStorageServer.java
- storage-nvmf/src/test/java/org/apache/crail/storage/nvmf/client/NvmfStagingBufferCacheTest.java
- storage-rdma/src/main/java/org/apache/crail/storage/rdma/RdmaConstants.java
- storage-rdma/src/main/java/org/apache/crail/storage/rdma/RdmaStorageServer.java
- storage/src/main/java/org/apache/crail/storage/StorageUtils.java
Better default values for cachepath and tcp storage path. Throw an
exception if paths are invalid. Throw an exception if interface is
invalid. Trim down crail-site.conf.template to only include the
necessary parameters.
https://issues.apache.org/jira/browse/CRAIL-15
Signed-off-by: Patrick Stuedi <pstuedi@apache.org>
> Make default configuration easier to run

- bin/crail
- conf/crail-env.sh.template
Remove Xmx and MaxDirectMemorySize argument from start script
since it does not allow to run Crail on machines with less
than 64G.
https://issues.apache.org/jira/browse/CRAIL-40
> Start script: remove heap size argument

- storage-narpc/src/main/java/org/apache/crail/storage/tcp/TcpStorageServer.java
- storage-rdma/src/main/java/org/apache/crail/storage/rdma/RdmaStorageServer.java
- storage-rdma/src/main/java/org/apache/crail/storage/rdma/client/RdmaStorageLocalEndpoint.java
- storage/src/main/java/org/apache/crail/storage/StorageUtils.java
permissions.
Fixes the issue of invalid datapath or missing write permissions on the
datapath for both the RDMA and the TCP storage tier.
https://issues.apache.org/jira/browse/CRAIL-45
Signed-off-by: Patrick Stuedi <pstuedi@apache.org>
> Throw more meaningful exception if datapath is invalid or has no write

- README.md
Remove content which is provided in readthedocs to avoid
keeping track of multiple location when updating the documentation.
Add a disclaimer that we are a incubator project.
Add badges for license and docs build status.
https://jira.apache.org/jira/projects/CRAIL/issues/CRAIL-36
https://jira.apache.org/jira/projects/CRAIL/issues/CRAIL-24
> README: remove content, add disclaimer

- docker/RDMA/Dockerfile
Fix base image url/tag and update DiSNI version to match version
in pom file.
https://jira.apache.org/jira/projects/CRAIL/issues/CRAIL-58
> Docker: fix base image url/tag and DiSNI version

- doc/source/iobench.rst
- doc/source/run.rst
- doc/source/shell.rst
Fix path to crail script. The correct path is $CRAIL_HOME/bin/crail
https://jira.apache.org/jira/browse/CRAIL-66
> [Documentation] fix path to crail script

- doc/source/source.rst
Clarify build instructions where to find tarball after a
successful build.
https://jira.apache.org/jira/browse/CRAIL-67
> [Documentation] clarify where to find tarball

- doc/Makefile
- doc/source/conf.py
- doc/source/config.rst
- doc/source/contact.rst
- doc/source/contribute.rst
- doc/source/deploy.rst
- doc/source/develop.rst
- doc/source/docker.rst
- doc/source/fsck.rst
- doc/source/index.rst
- doc/source/introduction.rst
- doc/source/iobench.rst
- doc/source/release.rst
- doc/source/run.rst
- doc/source/shell.rst
- doc/source/source.rst
- doc/source/spark.rst
- pom.xml
Add Apache license to documentation and do not exclude
doc folder from rat check anymore.
https://jira.apache.org/jira/browse/CRAIL-71
> [Documentation] add license, revert rat exclude

- pom.xml
Change name of source tarball to adhere to
apche-crail-X.Y-incubating-src
https://jira.apache.org/jira/projects/CRAIL/issues/CRAIL-56
> [Build] fix source tarball name

- doc/source/release.rst
Release process does not require to create checksum files
manually anymore.
https://jira.apache.org/jira/projects/CRAIL/issues/CRAIL-56
https://jira.apache.org/jira/projects/CRAIL/issues/CRAIL-61
> [Documentation] release process improved

- assembly/pom.xml
Append filename to checksum in checksum files. This allows to
check checksum with sha512sum -c <filename>
https://issues.apache.org/jira/projects/CRAIL/issues/CRAIL-73
> [Build] Append filename to checksum files

- assembly/src/main/assembly/source-assembly.xml
Add binary licenses to src tarball to allow to execute "mvn package"
which creates a binary tarball with said licenses.
> [Build] Fix source tarball not compiling

- storage-nvmf/src/main/java/org/apache/crail/storage/nvmf/client/NvmfStorageEndpoint.java
Appending the port to the subsystem NQN was introduced to allow
connecting to multiple targets on the same host. This problem occured
because we currently do not store subsystem NQN information at the
namenode, so there is only one global subsystem NQN in the configuration
file. For now we are removing this hack because it confuses users.
> [NVMf] do not append port to subsystem NQN

- doc/source/config.rst
- doc/source/run.rst
- storage-nvmf/src/main/java/org/apache/crail/storage/nvmf/NvmfStorageClient.java
- storage-nvmf/src/main/java/org/apache/crail/storage/nvmf/NvmfStorageConstants.java
- storage-nvmf/src/main/java/org/apache/crail/storage/nvmf/NvmfStorageServer.java
This adds a host NQN configuration parameter to allow setting the host NQN when connecting
to a NVMf target both from the client as from the datanode.
> NVMf Host nqn configuration parameter

- LICENSE-binary
- pom.xml
New DiSNI version fixes hang issue with Spark: https://issues.apache.org/jira/browse/CRAIL-98
Please, pull and test. It might take a while until DiSNI, DaRPC and jNVMf are available in maven central.
> DiSNI, DaRPC & jNVMf update

- docker/RDMA/Dockerfile
Automatically get libdisni version from DiSNI jar.
Before we had to manually update the DiSNI version
for building the native library on every release.
> Docker disni version

- storage-rdma/src/main/java/org/apache/crail/storage/rdma/RdmaStorageServer.java
Close StorageServer client endpoint if client disconnected.
Otherwise QP would persist in closed state.
> Fixes JIRA CRAIL-103

- storage-rdma/src/main/java/org/apache/crail/storage/rdma/RdmaStorageEndpointFactory.java
- storage-rdma/src/main/java/org/apache/crail/storage/rdma/RdmaStorageServer.java
- storage-rdma/src/main/java/org/apache/crail/storage/rdma/RdmaStorageServerEndpoint.java
The passive endpoint model caused an orphaned CQ at DataNode
after each client disconnect. Each new client connection caused
creation of another CQ. Changing to an active endpoint model
frees the per client CQ after client disconnect. Since the CQ is
not actually used (the endpoint handles only RDMA Read and
Write from client side), the active endpoint gets created with
minimum resources (send/receive/completion queue size == 1),
and the CQ event dispatcher is a nop.
Signed-off-by: Bernard Metzler <bmt@zurich.ibm.com>
> Make StoragerServer ep active to prevent orphaned CQ.

- storage-nvmf/src/main/java/org/apache/crail/storage/nvmf/NvmfStorageClient.java
Daemonize the keepalive thread to allow applications to
exit when the main method returns without closing the
storage client explicitly. For example, Spark has this
requirement.
https://issues.apache.org/jira/browse/CRAIL-98
> [NVMf] Make keepalive thread a daemon thread

- client/src/main/java/org/apache/crail/metadata/DataNodeStatistics.java
- client/src/main/java/org/apache/crail/metadata/DataNodeStatus.java
- client/src/main/java/org/apache/crail/rpc/RpcConnection.java
- client/src/main/java/org/apache/crail/rpc/RpcDispatcher.java
- client/src/main/java/org/apache/crail/rpc/RpcErrors.java
- client/src/main/java/org/apache/crail/rpc/RpcRemoveDataNode.java
- rpc-darpc/src/main/java/org/apache/crail/namenode/rpc/darpc/DaRPCNameNodeConnection.java
- rpc-darpc/src/main/java/org/apache/crail/namenode/rpc/darpc/DaRPCNameNodeRequest.java
- rpc-darpc/src/main/java/org/apache/crail/namenode/rpc/darpc/DaRPCNameNodeResponse.java
- rpc-narpc/src/main/java/org/apache/crail/namenode/rpc/tcp/TcpNameNodeRequest.java
- rpc-narpc/src/main/java/org/apache/crail/namenode/rpc/tcp/TcpNameNodeResponse.java
- rpc-narpc/src/main/java/org/apache/crail/namenode/rpc/tcp/TcpRpcConnection.java
- rpc/src/main/java/org/apache/crail/rpc/RpcProtocol.java
- rpc/src/main/java/org/apache/crail/rpc/RpcRequestMessage.java
- rpc/src/main/java/org/apache/crail/rpc/RpcResponseMessage.java
This PR is the first of three planned PRs for implementing resource elasticity within Crail. More specifically, the goal is to allow to automatically and dynamically adapt the number of running datanodes based on different possible parameters (e.g. resource consumption, available storage capacities, ...). This requires support for starting and terminating running datanodes automatically. This functionality will be implemented mostly within the Crail namenode. Therefore, the Crail namenode will not only maintain information on the current state of the datanodes and the deployment but will also start or terminate datanodes as required. For deciding how to adjust the number of datanodes  based on the current state observed in the Crail namenode so-called _policies_ are used. 
The following …
> Resource Elasticity [1/3]

- bin/crail
- client/src/main/java/org/apache/crail/tools/RemoveDataNode.java
- namenode/src/main/java/org/apache/crail/namenode/BlockStore.java
- namenode/src/main/java/org/apache/crail/namenode/DataNodeBlocks.java
- namenode/src/main/java/org/apache/crail/namenode/LogDispatcher.java
- namenode/src/main/java/org/apache/crail/namenode/NameNodeService.java
- rpc-darpc/src/main/java/org/apache/crail/namenode/rpc/darpc/DaRPCServiceDispatcher.java
- rpc-narpc/src/main/java/org/apache/crail/namenode/rpc/tcp/TcpRpcDispatcher.java
- rpc/src/main/java/org/apache/crail/rpc/RpcNameNodeService.java
- storage-narpc/src/main/java/org/apache/crail/storage/tcp/TcpStorageServer.java
- storage-nvmf/src/main/java/org/apache/crail/storage/nvmf/NvmfStorageServer.java
- storage-rdma/src/main/java/org/apache/crail/storage/rdma/RdmaStorageServer.java
- storage/src/main/java/org/apache/crail/storage/StorageServer.java
This PR is the second of three planned PRs for implementing resource elasticity within Crail. More specifically, the goal is to allow to automatically and dynamically adapt the number of running datanodes based on different possible parameters (e.g. resource consumption, available storage capacities, ...). This requires support for starting and terminating running datanodes automatically. This functionality will be implemented mostly within the Crail namenode. Therefore, the Crail namenode will not only maintain information on the current state of the datanodes and the deployment but will also start or terminate datanodes as required. For deciding how to adjust the number of datanodes  based on the current state observed in the Crail namenode so-called _policies_ are used. 
The following …
> Resource Elasticity [2/3]

- client/src/main/java/org/apache/crail/conf/CrailConstants.java
- namenode/src/main/java/org/apache/crail/namenode/BlockStore.java
- namenode/src/main/java/org/apache/crail/namenode/DataNodeBlocks.java
- namenode/src/main/java/org/apache/crail/namenode/ElasticNameNodeService.java
- namenode/src/main/java/org/apache/crail/namenode/FreeCapacityPolicy.java
- namenode/src/main/java/org/apache/crail/namenode/NameNode.java
- namenode/src/main/java/org/apache/crail/namenode/NameNodeService.java
- namenode/src/main/java/org/apache/crail/namenode/PolicyRunner.java
This PR is the third of three planned PRs for implementing resource elasticity within Crail. More specifically, the goal is to allow to automatically and dynamically adapt the number of running datanodes based on different possible parameters (e.g. resource consumption, available storage capacities, ...). This requires support for starting and terminating running datanodes automatically. This functionality will be implemented mostly within the Crail namenode. Therefore, the Crail namenode will not only maintain information on the current state of the datanodes and the deployment but will also start or terminate datanodes as required. For deciding how to adjust the number of datanodes  based on the current state observed in the Crail namenode so-called _policies_ are used. 
The following …
> Resource Elasticity [3/3]
